# Generated by Django 6.0.3 on 2026-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('engine', models.CharField(max_length=55)),
                ('mileage', models.IntegerField(default=0)),
                ('passenger_number', models.IntegerField(default=2)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_leased', models.BooleanField(default=True)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('leasing_price', models.FloatField(default=0.0)),
                ('registration_number', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
