# Generated by Django 6.0.3 on 2026-04-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_documenttype_application_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car'),
        ),
    ]
